# Generated by Django 5.2.6 on 2025-11-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id_visita', models.AutoField(primary_key=True, serialize=False)),
                ('entrada_at', models.DateTimeField(blank=True, null=True)),
                ('salida_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'visita',
                'managed': False,
            },
        ),
    ]
