# Generated by Django 5.2.6 on 2025-11-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id_lugar', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_lugar', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'lugar',
                'managed': False,
            },
        ),
    ]
