# Generated by Django 5.2.6 on 2025-11-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('nro_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('is_inside', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
    ]
